### ISSUE TITLE
Wrong lat_deg_arclen

### ISSUE THREAD

**Issue by mrhso** [Artoria2e5/PRCoords#10]
https://github.com/Artoria2e5/PRCoords/blob/master/js/PRCoords.js#L124
It should be `(Math.PI / 180) * (GCJ_A * (1 - GCJ_EE)) / Math.pow(magic, 1.5)`, instead of `(Math.PI / 180) * (GCJ_A * (1 - GCJ_EE)) * Math.pow(magic, 1.5)`.
The bug is in all languages except lua.
BTW, lon_deg_arclen (arclon) in Racket is also wrong.

**Comment by Artoria2e5** [comment]
the FUCK how did this thing work at all

**Comment by Artoria2e5** [comment]
fixed in 1.0.2

**Comment by mrhso** [comment]
Well, but...
https://github.com/Artoria2e5/PRCoords/blob/master/racket/prcoords.rkt#L111

**Comment by Artoria2e5** [comment]
yeah nah leave it for tomorrow..
