### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by zeroxia** [Artoria2e5/PRCoords#14]
Hello,

In [README.md](https://github.com/Artoria2e5/PRCoords/blob/master/README.md) it is stated the work in this repo is dual-licensed, may I confirm that does that mean I can ignore the `GPL` license and follow the [CC0 1.0 Public Domain Dedication](https://creativecommons.org/publicdomain/zero/1.0/) license?

For the CC0 license I believe it allows me to integrate the code in this repo and not release my code to pubic?

Thanks for all these great work!

**Comment by Artoria2e5** [comment]
Yes you may ignore the GPL. It was put there for fun.
