### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by zeroxia** [Artoria2e5/PRCoords#15]
Hi,

Not sure if this is due to my environment.

The demo page (https://artoria2e5.github.io/PRCoords/demo.html) does not work, it fails to load "https://cdn.jsdelivr.net/npm/prcoords@1//js/PRCoords.min.js".

Note that there is `//` in the URL, visiting it directly in browser would get HTTP 400, opening the demo page and check browser console in developer tools also shows this error.

If I remove one slash, the URL is valid.

**Comment by Artoria2e5** [comment]
Huh, it used to work…
